DECLARE @FILENAME VARCHAR(255)  

SELECT @FILENAME = SUBSTRING(PATH, 0, LEN(PATH)-CHARINDEX('\', REVERSE(PATH))+1) + '\LOG.TRC'   

FROM SYS.TRACES    

WHERE IS_DEFAULT = 1;   

  

--SELECT @FILENAME 

  

SELECT GT.HOSTNAME,  

       GT.APPLICATIONNAME,  

       GT.NTUSERNAME,  

       GT.NTDOMAINNAME,  

       GT.LOGINNAME,  

       GT.SPID,  

       GT.EVENTCLASS,  

       TE.NAME AS EVENTNAME, 

       GT.EVENTSUBCLASS,       

       GT.TEXTDATA,  

       GT.STARTTIME,  

       GT.ENDTIME,  

       GT.OBJECTNAME,  

       GT.DATABASENAME,  

       GT.FILENAME,  

       GT.ISSYSTEM, 

       O.TYPE_DESC 

FROM [FN_TRACE_GETTABLE](@FILENAME, DEFAULT) GT  

INNER JOIN SYS.TRACE_EVENTS TE ON GT.EVENTCLASS = TE.TRACE_EVENT_ID 

INNER JOIN SYS.OBJECTS O ON GT.OBJECTID=O.OBJECT_ID 

WHERE EVENTCLASS NOT IN (175,116,79,69,55,46) 

AND EVENTCLASS IN (164) --Object:Altered  

AND O.TYPE IN ('P','FN') --'P' for Stored Procedure, 'FN' for Function 

--AND GT.EVENTSUBCLASS IN (0,1) 

--AND GT.NTUSERNAME LIKE 'GO%' 

--AND GT.OBJECTNAME = 'SPR_Test' 

ORDER BY STARTTIME DESC;  